local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")

local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:WaitForChild("PlayerGui")

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "WindUI"
ScreenGui.IgnoreGuiInset = true
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
ScreenGui.Parent = PlayerGui

local MainFrame = Instance.new("Frame")
MainFrame.Size = UDim2.new(0, 330, 0, 400)
MainFrame.Position = UDim2.new(0.04, 0, 0.18, 0)
MainFrame.BackgroundColor3 = Color3.fromRGB(26, 26, 31)
MainFrame.BorderSizePixel = 0
MainFrame.ClipsDescendants = true
MainFrame.CornerRadius = UDim.new(0, 8)
MainFrame.Parent = ScreenGui

local TitleBar = Instance.new("Frame")
TitleBar.Size = UDim2.new(1, 0, 0, 34)
TitleBar.BackgroundColor3 = Color3.fromRGB(38, 38, 45)
TitleBar.CornerRadius = UDim.new(0, 8)
TitleBar.Parent = MainFrame

local TitleLabel = Instance.new("TextLabel")
TitleLabel.Size = UDim2.new(1, -75, 1, 0)
TitleLabel.Position = UDim2.new(0, 12, 0, 0)
TitleLabel.BackgroundTransparency = 1
TitleLabel.Text = "WindUI Panel"
TitleLabel.Font = Enum.Font.Inter
TitleLabel.TextSize = 14
TitleLabel.TextXAlignment = Enum.TextXAlignment.Left
TitleLabel.TextColor3 = Color3.new(1,1,1)
TitleLabel.Parent = TitleBar

local MinButton = Instance.new("TextButton")
MinButton.Size = UDim2.new(0, 26, 0, 26)
MinButton.Position = UDim2.new(1, -64, 0, 4)
MinButton.BackgroundColor3 = Color3.fromRGB(55, 55, 65)
MinButton.Text = "_"
MinButton.Font = Enum.Font.InterBold
MinButton.TextSize = 16
MinButton.TextColor3 = Color3.new(1,1,1)
MinButton.CornerRadius = UDim.new(0,5)
MinButton.Parent = TitleBar

local CloseButton = Instance.new("TextButton")
CloseButton.Size = UDim2.new(0, 26, 0, 26)
CloseButton.Position = UDim2.new(1, -32, 0, 4)
CloseButton.BackgroundColor3 = Color3.fromRGB(170, 60, 60)
CloseButton.Text = "X"
CloseButton.Font = Enum.Font.InterBold
CloseButton.TextSize = 14
CloseButton.TextColor3 = Color3.new(1,1,1)
CloseButton.CornerRadius = UDim.new(0,5)
CloseButton.Parent = TitleBar

local function WindButton(Y, Text, Color)
	local Button = Instance.new("TextButton")
	Button.Size = UDim2.new(0.84, 0, 0, 42)
	Button.Position = UDim2.new(0.08, 0, 0, Y)
	Button.BackgroundColor3 = Color
	Button.Text = Text
	Button.Font = Enum.Font.Inter
	Button.TextSize = 14
	Button.TextColor3 = Color3.new(1,1,1)
	Button.BorderSizePixel = 0
	Button.CornerRadius = UDim.new(0,6)
	Button.Parent = MainFrame

	Button.MouseEnter:Connect(function()
		TweenService:Create(Button,TweenInfo.new(0.18),{BackgroundColor3 = Color:Lerp(Color3.new(1,1,1),Color,0.75)}):Play()
	end)
	Button.MouseLeave:Connect(function()
		TweenService:Create(Button,TweenInfo.new(0.18),{BackgroundColor3 = Color}):Play()
	end)
	return Button
end

local Btn1 = WindButton(48, "功能一", Color3.fromRGB(44, 64, 94))
local Btn2 = WindButton(98, "功能二", Color3.fromRGB(38, 80, 62))
local Btn3 = WindButton(148, "功能三", Color3.fromRGB(90, 62, 44))
local SpawnCarBtn = WindButton(198, "生成载具 TIV 2 2009", Color3.fromRGB(34,78,76))

Btn1.MouseButton1Click:Connect(function()
	print("执行功能一")
end)
Btn2.MouseButton1Click:Connect(function()
	print("执行功能二")
end)
Btn3.MouseButton1Click:Connect(function()
	print("执行功能三")
end)

SpawnCarBtn.MouseButton1Click:Connect(function()
-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt
local Event = game:GetService("ReplicatedStorage").SpawnCar
Event:FireServer("TIV 2 2009")
	print("发送载具生成请求 TIV 2 2009")
end)

local Minimized = false
local BaseHeight = 400
local MiniHeight = 34
MinButton.MouseButton1Click:Connect(function()
	Minimized = not Minimized
	local TargetH = Minimized and MiniHeight or BaseHeight
	MinButton.Text = Minimized and "□" or "_"
	TweenService:Create(MainFrame,TweenInfo.new(0.22),{Size=UDim2.new(0,330,0,TargetH)}):Play()
end)

CloseButton.MouseButton1Click:Connect(function()
	ScreenGui:Destroy()
end)

local dragging = false
local StartInputPos
local StartUIPos

TitleBar.InputBegan:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
		dragging = true
		StartInputPos = input.Position
		StartUIPos = MainFrame.Position
	end
end)

UserInputService.InputChanged:Connect(function(input)
	if not dragging then return end
	if input.UserInputType ~= Enum.UserInputType.MouseMovement and input.UserInputType ~= Enum.UserInputType.Touch then return end

	local Delta = input.Position - StartInputPos
	MainFrame.Position = UDim2.new(
		StartUIPos.X.Scale, StartUIPos.X.Offset + Delta.X,
		StartUIPos.Y.Scale, StartUIPos.Y.Offset + Delta.Y
	)
end)

UserInputService.InputEnded:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
		dragging = false
	end
end)
